'use client';

import {
  Calendar,
  Clock,
  Users,
  Settings,
  Trophy,
  Ticket,
  BarChart3,
  Eye,
  MessageCircle,
  CheckCircle,
  FileText,
  CreditCard,
  MapPin,
  Phone,
  Mail,
  DollarSign,
  TrendingUp,
  AlertCircle,
  CalendarDays,
  ChevronRight,
  ExternalLink,
  LogOut,
  Menu,
  X,
  Plus,
  Edit,
  Trash2,
  Search,
  Filter,
  Download,
  RefreshCw,
  ChevronLeft,
  ChevronDown,
  Info,
  AlertTriangle,
  Check,
  XCircle,
  Ban,
  Timer,
  Wallet,
  QrCode,
  Building2,
  User,
  PhoneCall,
  Send,
  Copy,
  Share2,
  Home,
  LayoutDashboard,
  Landmark,
  Zap,
  Image,
  Pin,
  Sparkles,
  Hourglass,
  Smartphone,
  Target,
} from 'lucide-react';

export const Icons = {
  calendar: Calendar,
  clock: Clock,
  users: Users,
  settings: Settings,
  trophy: Trophy,
  ticket: Ticket,
  chart: BarChart3,
  eye: Eye,
  message: MessageCircle,
  check: CheckCircle,
  fileText: FileText,
  creditCard: CreditCard,
  mapPin: MapPin,
  phone: Phone,
  mail: Mail,
  dollar: DollarSign,
  trendingUp: TrendingUp,
  alertCircle: AlertCircle,
  calendarDays: CalendarDays,
  court: Landmark,
  chevronRight: ChevronRight,
  externalLink: ExternalLink,
  logout: LogOut,
  menu: Menu,
  close: X,
  plus: Plus,
  edit: Edit,
  trash: Trash2,
  search: Search,
  filter: Filter,
  download: Download,
  refresh: RefreshCw,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  info: Info,
  alertTriangle: AlertTriangle,
  checkIcon: Check,
  xCircle: XCircle,
  ban: Ban,
  timer: Timer,
  wallet: Wallet,
  qrCode: QrCode,
  building: Building2,
  user: User,
  phoneCall: PhoneCall,
  send: Send,
  copy: Copy,
  share: Share2,
  home: Home,
  dashboard: LayoutDashboard,
  zap: Zap,
  image: Image,
  pin: Pin,
  sparkles: Sparkles,
  hourglass: Hourglass,
  smartphone: Smartphone,
  target: Target,
};

export type IconName = keyof typeof Icons;

interface IconProps {
  name: IconName;
  className?: string;
  size?: number;
}

export function Icon({ name, className = '', size = 20 }: IconProps) {
  const IconComponent = Icons[name];
  return <IconComponent className={className} size={size} />;
}
